### ISSUE TITLE
ViewModel.onCleared() is not called

### ISSUE THREAD

**Issue by gmk57** [sebaslogen/resaca#1]
Thanks for this library, it might be very helpful. :+1:

Small gotcha: `ScopedViewModelContainer.scheduleToDispose()` calls `viewModelScope.cancel()`, but does not call `clear()` or `onCleared()` on scoped `ViewModel`s. It think it should, if possible (these methods are not public, unfortunately).

**Comment by sebaslogen** [comment]
Good point, I´ll take a look at a Java workaround to call protected methods.
Thanks for the suggestion.

**Comment by sebaslogen** [comment]
Fixed and release as hotfix version 1.1.1 https://github.com/sebaslogen/resaca/releases/tag/1.1.1

**Comment by gmk57** [comment]
Hmm, I've added some logs to `FakeScopedViewModel`, navigated back and forth, but `onCleared` wasn't called.

It seems `ScopedViewModelContainer` only calls `ViewModelClearer` in `scheduleToDispose`, not in its own `onCleared`.

In my fist message, I missed the fact that there are two "cleanup" places, unfortunately.

BTW, maybe it's better to extract common logic, to handle `is CoroutineScope` and `is CoroutineContext` cases too?

**Comment by sebaslogen** [comment]
> Hmm, I've added some logs to `FakeScopedViewModel`, navigated back and forth, but `onCleared` wasn't called.
> 
> It seems `ScopedViewModelContainer` only calls `ViewModelClearer` in `scheduleToDispose`, not in its own `onCleared`.
> 
> In my fist message, I missed the fact that there are two "cleanup" places, unfortunately.
> 
> BTW, maybe it's better to extract common logic, to handle `is CoroutineScope` and `is CoroutineContext` cases too?

Thanks for finding this bug.

Yes, I was thinking about the same solution, the logic should be all moved to a single clean up method and I'll add support for the Closeable interface like ViewModel does.

I'll also add some tests to make it more robust.

**Comment by sebaslogen** [comment]
I've fixed the points above and added a test. Let me know what you think and if you don't find anything I'll create a new release.

**Comment by gmk57** [comment]
Looks good to me. :)
Probably [this README section](https://github.com/sebaslogen/resaca#alternative-manual-installation) should be updated too.
I wish Google and JetBrains fixed their bugs that fast... ;)

**Comment by sebaslogen** [comment]
Wonderful, thanks for the doc update tip, you're 💯  awesome

Release https://github.com/sebaslogen/resaca/releases/tag/1.1.2 closes this ticket
