### ISSUE TITLE
Access to saved state handle inside factory function

### ISSUE THREAD

**Issue by TomBell-Trove** [sebaslogen/resaca#161]
Hi, due to past/tech debt reasons the app I maintain uses hand-rolled dependency management.

As a feature request (assuming it's not a thing right now) could you supply/expose the SavedStateHandle in the VM factory?

eg.
```
val vm = viewModelScoped(
    key = key,
    defaultArguments = myDefaultArgs,
) { handle: SavedStateHandle ->
    MyViewModel(
        handle = handle,
        myDependency = someDependency,
    )
}
```

**Comment by sebaslogen** [comment]
TBH, I don't know because resaca doesn't do anything with SavedStateHandle itself, it just relies on dagger, hilt,etc features.
But that doesn't mean it's impossible, I'll take a look on Friday.

**Comment by sebaslogen** [comment]
At the end it was possible so it's now part of release 4.4.0

**Comment by TomBell-Trove** [comment]
You legend! Code looks good too :) Thank you!
