### ISSUE TITLE
wrong dependency name in README

### ISSUE THREAD

**Issue by MichalSmiech** [sebaslogen/resaca#48]
It's:
`io.github.sebaslogen.resaca:resaca:X.X.X`

Should be:
`io.github.sebaslogen.resaca:X.X.X`

**Comment by sebaslogen** [comment]
@MichalSmiech thanks a lot! I'll fix all the references

**Comment by sebaslogen** [comment]
Fixed on https://github.com/sebaslogen/resaca/commit/f739e483136158a2a9b73ec4889548c1246d7ce9
