### ISSUE TITLE
Crash in Preview

### ISSUE THREAD

**Issue by smiLLe** [sebaslogen/resaca#58]
Hello, I am new to Android Dev and so I might do something wrong here :)
I thought this code should work in Previews but it will result in the error below.
I am using  version `3.2.0`

```kotlin
class IamScoped(var str: String = "OK") : ViewModel()

@Composable
fun ScopedVm() {
    val vm: IamScoped = viewModelScoped()
    Text(vm.str)
}
@Preview
@Composable
fun ScopedVmPreview() {
    ScopedVm()
}
```

```
_layoutlib_._internal_.kotlin.UninitializedPropertyAccessException: 
lateinit property viewModelProvider has not been initialized   at com.sebaslogen.resaca.ScopedViewModelProvider.getViewModelProvider(ScopedViewModelProvider.kt:33)
```

**Comment by sebaslogen** [comment]
Hi there!
Indeed, trying to use a ViewModel in a Preview will fail because Previews can't provide ViewModels with their dependencies.

This is explained in more detail in the official docs, with suggestions on how to use Previews without ViewModels: 
https://developer.android.com/jetpack/compose/tooling/previews#preview-viewmodel

**Comment by ninovanhooff** [comment]
@sebaslogen 

How about checking for LocalInspectionMode?

This works for me (in a case without dependencies):

```
@Composable
public inline fun <reified T : ViewModel, K : Any> viewModelScopedSafe(
  key: K,
  noinline keyInScopeResolver: KeyInScopeResolver<K>,
  defaultArguments: Bundle = Bundle.EMPTY,
  noinline builder: @DisallowComposableCalls () -> T
): T {
  return if (LocalInspectionMode.current) {
    builder()
  } else {
    viewModelScoped(key = key, keyInScopeResolver = keyInScopeResolver, defaultArguments = defaultArguments, builder = builder)
  }
}
```

**Comment by sebaslogen** [comment]
> @sebaslogen 
> 
> How about checking for LocalInspectionMode?
> 
> This works for me (in a case without dependencies):
> 
> ```
> @Composable
> public inline fun <reified T : ViewModel, K : Any> viewModelScopedSafe(
>   key: K,
>   noinline keyInScopeResolver: KeyInScopeResolver<K>,
>   defaultArguments: Bundle = Bundle.EMPTY,
>   noinline builder: @DisallowComposableCalls () -> T
> ): T {
>   return if (LocalInspectionMode.current) {
>     builder()
>   } else {
>     viewModelScoped(key = key, keyInScopeResolver = keyInScopeResolver, defaultArguments = defaultArguments, builder = builder)
>   }
> }
> ```

Unfortunately, this would still fail in most non-trivial cases, like with Hilt or other dependency injection frameworks.

On the other hand, this exception on Previews promotes using previews with the right kind of Composables, stateless Composables.

In any case, thank you @ninovanhooff for the suggestion

**Comment by ninovanhooff** [comment]
Allright, I guess I don't understand what the documentation is getting at when they talk about stateless composables.

See this sample snippet:

```kotlin
    val keys = rememberKeysInScope(inputListOfKeys = items)

    HorizontalPager(
      state = pagerState,
      flingBehavior = PagerDefaults.flingBehavior(
        state = pagerState,
        // because we have nested scrolling in the page content, we should
        // snap super quick when approaching the end state to unblock vertical scrolling.
        // if this is not appreciated we might use a spring() with a visibility threshold
        snapAnimationSpec = tween(
          easing = FastOutSlowInEasing,
          durationMillis = 100
        ),
      )
    ) { pageIdx ->
      val pageVM: TourPageViewModel = viewModelScopedSafe(
        key = items[pageIdx],
        keyInScopeResolver = keys,
        builder = { TourPageViewModel(items[pageIdx], pageIdx) }
      )
      // Our page content
      TourBrowserPage(
        viewState = pageVM.viewState, // pageVM.viewState is a simple data class for now
        isPlaying = isPlaying,
        onPlayPauseClicked = onPlayPauseClicked,
        onLayerClicked = onLayerClicked,
        onSeekBackClicked = onSeekBackClicked,
        onSeekForwardClicked = onSeekForwardClicked
      )
    }
    ```
    
If you ask me, TourBrowserPage is stateless. HorizontalPager is not, because it contains the resaca code to get a VM.

But how to crate a Preview for this snippet, I don't understand.
