### ISSUE TITLE
minSdkVersion 21

### ISSUE THREAD

**Issue by meruiden** [sebaslogen/resaca#7]
Hi,

Is there a specific reason this library targets a minimum of sdk 28? Our app doesn't compile because we're targeting minSdkVersion 21.

would it be safe to use
```<uses-sdk tools:overrideLibrary="com.sebaslogen.resaca"/>``` 
for this library?

Thanks!

**Comment by sebaslogen** [comment]
Definitely a mistake, probably introduced in the migration to gradle kts.
I'll fix it and release later on today.

Your workaround should work.

Thanks for reporting.

**Comment by sebaslogen** [comment]
This is fixed in release https://github.com/sebaslogen/resaca/releases/tag/2.4.1
